### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by vnprak** [vnprak/Electronic-Board-Game#1]
- [x] Create repository
- [x] Add collaborators
- [x] Set up Milestones
- [x] Set up Labels
- [x] Associate with Project

**Comment by vnprak** [comment]
Issues to be labeled by difficulty, category, and completion

**Comment by ffund** [comment]
@vnprak I'm not sure "completion status" should be a label - isn't that what the "status" in the Project board is for?
