### ISSUE TITLE
Check part "liveness" for LED and LED driver system

### ISSUE THREAD

**Issue by vnprak** [vnprak/Electronic-Board-Game#5]
How do you check liveness of shift registers?

In NYU Classes > CompE DP 1 > Lessons > 8 and 9 Serial Communication - review SPI stuff in lecture slides on Communication Protocols. 

In NYU Classes > CompE DP 1 > Lessons > 12 ADC, multiplexing - look at lecture recording starting at time 33:00. Also look at the lab material on pin multiplexing - the datasheet for the shift register is also there, and some demo code.

**Comment by ffund** [comment]
To check that the whole system is "alive": do the lab assignment section on shift register and LEDs, and make sure it works as expected.

**Comment by vnprak** [comment]
https://imgur.com/AEHDNQp

In this picture I have the first shift register representing the red signal for the LEDs, the second SR is green, third is blue. Ran out of wires but the idea here is that I will cycle all the LEDs through the colors red green and blue and then have each individual LED light up white and that should be sufficient to demonstrate that the registers and LEDs are alive

I will need more wires
