### ISSUE TITLE
Write setup.py

### ISSUE THREAD

**Issue by vnprak** [vnprak/Electronic-Board-Game#6]
In Brightspace, look at Content > Using Your New Parts > Infrastructure Layer, slide 5.

**Comment by ffund** [comment]
Also create a blank library file (Python file which is the module that's installed by `setup.py`). As you add stub functions, they'll go in there, and you'll test them by running:

```
sudo python3 setup.py install # install library
python3 demo.py # run demo.py that calls each stub function, to test it
```
